apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sre-lab-api
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/yerimm99/kind-sre-lab.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: sre-lab

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
