name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build FastAPI Docker image
        run: docker build -t kind-sre-lab-api:ci ./app

  kubernetes-validate:
    name: Kubernetes YAML Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install kubeconform
        run: |
          curl -L -o kubeconform.tar.gz https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz
          tar -xzf kubeconform.tar.gz
          sudo mv kubeconform /usr/local/bin/kubeconform

      - name: Validate Kubernetes manifests
        run: |
          kubeconform -strict -summary k8s/*.yaml

  terraform-validate:
    name: Terraform Validate
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/k8s-baseline

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate
